apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
  selector:
    app: mongo-express
  type: LoadBalancer
  ports:
  - port: {{ .Values.mongoExpress.servicePort }}
    targetPort: {{ .Values.mongoExpress.servicePort }}
    nodePort: {{ .Values.mongoExpress.nodePort }}
